services:
  - type: web
    name: mental-health-api
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install gdown
    startCommand: bash startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
